#!/bin/bash

set -e

fail() {
	echo "$*" >&2
	exit 1
}

[[ $# -gt 0 ]] || fail "Usage: gpio-unexport GPIOS..."

set -- `gpio-parse --kernel -- "$@"`

cd /sys/class/gpio

for i in "$@"; do
	if [[ -e gpio$i ]]; then
		echo $i >unexport
	fi
done
